import csv,json
from pathlib import Path
RUN=Path(__file__).resolve().parents[1]; ROOT=RUN.parents[2]; E26=ROOT/'experiment_outputs/metric_aligned_agent_phase_e26/run_20260820T113331_CST_quota_recovered_sol_xhigh_v1'; E27=ROOT/'experiment_outputs/metric_aligned_agent_phase_e27/run_20260822T000000_CST_frozen_multi_interface_fusion_v1'; E29R=ROOT/'experiment_outputs/metric_aligned_agent_phase_e29r/run_20260822T_continuation_one_call_stage_c_v1'; E30=ROOT/'experiment_outputs/metric_aligned_agent_phase_e30/run_20260822T194845_CST_offline_conditional_policy_v1'
def rr(p):
 with open(p,newline='') as f:return list(csv.DictReader(f))
def main():
 base=rr(E26/'evaluation/results/e26_canonical_predictions.csv'); e27={r['canonical_id']:r['winner_prediction'] for r in rr(E27/'results/e27_winner_canonical_predictions.csv')}; e29={r['canonical_id']:r['prediction'] for r in rr(E29R/'results/stage_c_winner_canonical_predictions.csv')}; e30={r['canonical_id']:r['prediction'] for r in rr(E30/'results/e30_absolute_winner_canonical_predictions.csv')}; target={r['canonical_id']:r for r in rr(E29R/'targets/target_pool.csv')}; cache={p.stem:json.loads(p.read_text()) for p in (E29R/'caches/ADJUDICATOR').glob('*.json')}; out=[]
 for r in base:
  cid=r['canonical_id']; c=cache.get(cid,{}).get('output',{}); t=target.get(cid,{}); i1=int(r.get('i1_reason_prediction','-1') or -1); i2=int(r.get('i2_reason_prediction','-1') or -1); i3=int(r.get('i3_reason_prediction','-1') or -1); labels=[x for x in (i1,i2,i3) if x>=0]; support=max([labels.count(x) for x in set(labels)] or [0]); out.append({'canonical_id':cid,'full_prediction':int(r['full_prediction']),'d3_prediction':int(r['residual_prediction']),'e26_prediction':i3,'e27_prediction':int(e27[cid]),'e29r_prediction':int(e29[cid]),'e30_prediction':int(e30[cid]),'i1_label':i1,'i2_label':i2,'i3_label':i3,'i1_decision':r.get('i1_decision',''),'i2_decision':r.get('i2_decision',''),'i3_decision':r.get('i3_decision',''),'adjudicator_final_label':({'ang':0,'sad':1,'hap':2,'neu':3,'exc':4,'fru':5}.get(c.get('final_label'),-1)),'adjudicator_decision':c.get('decision',''),'adjudicator_confidence':float(c.get('confidence',0) or 0),'adjudicator_uncertainty':float(c.get('uncertainty',1) if c.get('uncertainty') is not None else 1),'adjudicator_preferred_source':c.get('preferred_source',''),'evidence_consistency':c.get('evidence_consistency',''),'target_pool_order':int(t.get('bucket_rank',9999)),'support':support,'in_target':cid in target})
 if len(out)!=1623 or len({r['canonical_id'] for r in out})!=1623:raise RuntimeError('feature count failure')
 (RUN/'stage_c/features.json').write_text(json.dumps(out,separators=(',',':'))); (RUN/'stage_c/materialized/e30_winner_predictions.csv').write_text('canonical_id,prediction\n'+'\n'.join(f"{r['canonical_id']},{r['e30_prediction']}" for r in out)+'\n'); forbidden=('gold','benefit','harm','outcome','wf1','metric','oracle'); text=json.dumps(out).lower()
 if any(x in text for x in forbidden):raise RuntimeError('forbidden materialization feature')
 (RUN/'metadata/FEATURES_MANIFEST.json').write_text(json.dumps({'canonical_count':1623,'gold_in_features':False,'reasoner_api_calls':0},indent=2));print(json.dumps({'canonical_count':1623,'target_count':sum(r['in_target'] for r in out)}))
if __name__=='__main__':main()
